mklink /H "C:\cygwin64\home\gduarte\.bash_profile" "./zsh/.bash_profile"
mklink /H "C:\cygwin64\home\gduarte\.bashrc" "./zsh/.bashrc
mklink /H "C:\cygwin64\home\gduarte\.profile" "zsh/.profile"
mklink /H "C:\cygwin64\home\gduarte\.zpreztorc" "zsh/.zpreztorc"
mklink /H "C:\cygwin64\home\gduarte\.zshrc" "zsh/.zshrc"
mklink /H "C:\cygwin64\home\gduarte\.gitconfig" ".gitconfig"
mklink /H "%userprofile%\.czrc" ".czrc"
mklink /H "%userprofile%\.gitconfig" ".gitconfig"
mklink /H "%userprofile%\.hyper.js" ".hyper.js"