git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
# os:
#   editCommand: "nvim"
#   editCommandTemplate: "{{editor}} --server $NVIM --remote-tab {{filename}}"
# os:
#   editPreset: "nvim"
