git:
  ignoreWhitespaceInDiffView: true
  diffRenderers:
    - colorArg: always
      command: delta --dark --paging=never
promptToReturnFromSubprocess: false
# os:
#   editCommand: "nvim"
#   editCommandTemplate: "{{editor}} --server $NVIM --remote-tab {{filename}}"
# os:
#   editPreset: "nvim"
