# Setup:
#   sudo mkdir -p /etc/keyd
#   sudo ln -sf ~/.config/keyd/default.conf /etc/keyd/default.conf
#   sudo systemctl enable --now keyd
#   sudo keyd reload

[ids]
*

[main]
capslock = overloadt2(fn, capslock, 200)

[fn]
# arrows
j = left
k = down
l = right
i = up

# media
f1 = mute
f2 = volumedown
f3 = volumeup
f4 = micmute

# brightness
f5 = brightnessdown
f6 = brightnessup
f7 = switchvideomode

# f-keys
f10 = f16
f11 = f23
f12 = favorites

# screenshot
f9 = print
] = print
