# Setup:
#   sudo mkdir -p /etc/keyd
#   sudo ln -sf ~/.config/keyd/default.conf /etc/keyd/default.conf
#   sudo systemctl enable --now keyd
#   sudo keyd reload

[ids]
*

[main]
capslock = overload(nav, capslock)

[nav]
j = left
k = down
l = right
i = up
