return {
  "williamboman/mason.nvim",
  opts = {
    ensure_installed = {
      "astro-language-server",
      "bash-language-server",
      "css-lsp",
      "css-variables-language-server",
      "cssmodules-language-server",
      "docker-compose-language-service",
      "dockerfile-language-server",
      "eslint-lsp",
      "graphql-language-service-cli",
      "hyprls",
      "json-lsp",
      "lua-language-server",
      "markdown-toc",
      "markdownlint-cli2",
      "marksman",
      "prettierd",
      "shellcheck",
      "shfmt",
      "stylua",
      "yaml-language-server",
    },
  },
}
